# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eec1b3ba2a36b07234fe01de7cee607a815101a202b9a918d6957373e10354266692a2c53340b471e6eea93ad30d79108909d3f84fdd4b22b9f00cf08f6a1f64

test:
  secret_key_base: d556b005c5575e06ec9022ed7b672bed89e08ef0525789a91b1ca35f91dbb0328b1690124e7c1e26b367caf07f0d72c862e95e8279474312cb7145e5c064a147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
